<?php

namespace Database\Seeders;

use App\Models\Link;
use Illuminate\Database\Seeder;

class LinkSeeder extends Seeder
{
    public function run(): void
    {
        Link::truncate();

        $links = [
            // ─── Sosial Media (1–5) ──────────────────────────────────
            [
                'judul'      => 'Instagram',
                'slug'       => 'instagram',
                'url'        => 'https://instagram.com',
                'deskripsi'  => 'Ikuti Instagram Rizki Habibi untuk konten sehari-hari dan update terbaru.',
                'ikon'       => '📸',
                'warna_bg'   => '#E1306C',
                'warna_teks' => '#FFFFFF',
                'urutan'     => 1,
                'aktif'      => true,
            ],
            [
                'judul'      => 'TikTok',
                'slug'       => 'tiktok',
                'url'        => 'https://tiktok.com',
                'deskripsi'  => 'Tonton video pendek, tutorial coding, dan konten kreatif Rizki Habibi.',
                'ikon'       => '🎵',
                'warna_bg'   => '#010101',
                'warna_teks' => '#FFFFFF',
                'urutan'     => 2,
                'aktif'      => true,
            ],
            [
                'judul'      => 'YouTube — 26 Rizki Habibi',
                'slug'       => 'youtube',
                'url'        => 'https://www.youtube.com/@26_rizkihabibi73',
                'deskripsi'  => 'Subscribe @26_rizkihabibi73 — tutorial coding, project, dan konten teknologi.',
                'ikon'       => '▶️',
                'warna_bg'   => '#FF0000',
                'warna_teks' => '#FFFFFF',
                'urutan'     => 3,
                'aktif'      => true,
                'unggulan'   => true,
            ],
            [
                'judul'      => 'Twitter / X',
                'slug'       => 'twitter-x',
                'url'        => 'https://twitter.com',
                'deskripsi'  => 'Ikuti Twitter/X Rizki Habibi untuk update singkat dan diskusi teknologi.',
                'ikon'       => '🐦',
                'warna_bg'   => '#1DA1F2',
                'warna_teks' => '#FFFFFF',
                'urutan'     => 4,
                'aktif'      => true,
            ],
            [
                'judul'      => 'Facebook',
                'slug'       => 'facebook',
                'url'        => 'https://facebook.com',
                'deskripsi'  => 'Ikuti halaman Facebook Rizki Habibi untuk update dan konten terbaru.',
                'ikon'       => '👍',
                'warna_bg'   => '#1877F2',
                'warna_teks' => '#FFFFFF',
                'urutan'     => 5,
                'aktif'      => true,
            ],

            // ─── Komunitas & Chat (6–8) ──────────────────────────────
            [
                'judul'      => 'WhatsApp',
                'slug'       => 'whatsapp',
                'url'        => 'https://wa.me/6281234567890',
                'deskripsi'  => 'Hubungi Rizki Habibi via WhatsApp untuk kolaborasi atau ngobrol santai.',
                'ikon'       => '💬',
                'warna_bg'   => '#25D366',
                'warna_teks' => '#FFFFFF',
                'urutan'     => 6,
                'aktif'      => true,
            ],
            [
                'judul'      => 'Telegram',
                'slug'       => 'telegram',
                'url'        => 'https://t.me/contoh',
                'deskripsi'  => 'Gabung channel Telegram Rizki Habibi untuk info dan diskusi komunitas.',
                'ikon'       => '✈️',
                'warna_bg'   => '#229ED9',
                'warna_teks' => '#FFFFFF',
                'urutan'     => 7,
                'aktif'      => true,
            ],
            [
                'judul'      => 'Discord Server',
                'slug'       => 'discord',
                'url'        => 'https://discord.gg/contoh',
                'deskripsi'  => 'Join server Discord Rizki Habibi — ngobrol, gaming, dan kolaborasi bareng!',
                'ikon'       => '🎮',
                'warna_bg'   => '#5865F2',
                'warna_teks' => '#FFFFFF',
                'urutan'     => 8,
                'aktif'      => true,
            ],

            // ─── Marketplace (9–11) ──────────────────────────────────
            [
                'judul'      => 'Toko Shopee — Promo Terbaru',
                'slug'       => 'shopee',
                'url'        => 'https://shopee.co.id',
                'deskripsi'  => 'Promo flash sale dan diskon terbaik di toko Shopee Rizki Habibi.',
                'ikon'       => '🛍️',
                'warna_bg'   => '#EE4D2D',
                'warna_teks' => '#FFFFFF',
                'urutan'     => 9,
                'aktif'      => true,
            ],
            [
                'judul'      => 'Toko Tokopedia',
                'slug'       => 'tokopedia',
                'url'        => 'https://tokopedia.com',
                'deskripsi'  => 'Belanja aman dan pengiriman cepat di Tokopedia Rizki Habibi.',
                'ikon'       => '🟢',
                'warna_bg'   => '#03AC0E',
                'warna_teks' => '#FFFFFF',
                'urutan'     => 10,
                'aktif'      => true,
            ],
            [
                'judul'      => 'Toko Lazada — Harga Murah',
                'slug'       => 'lazada',
                'url'        => 'https://lazada.co.id',
                'deskripsi'  => 'Belanja produk murah berkualitas di Lazada — penawaran terbaik & gratis ongkir!',
                'ikon'       => '🛒',
                'warna_bg'   => '#0F146D',
                'warna_teks' => '#FFFFFF',
                'urutan'     => 11,
                'aktif'      => true,
            ],

            // ─── Profesional (12–16) ────────────────────────────────
            [
                'judul'      => 'GitHub — Rizki Habibi',
                'slug'       => 'github',
                'url'        => 'https://github.com/rizki-habibi',
                'deskripsi'  => 'Lihat semua project open-source dan repositori Rizki Habibi di GitHub.',
                'ikon'       => '💻',
                'warna_bg'   => '#24292E',
                'warna_teks' => '#FFFFFF',
                'urutan'     => 12,
                'aktif'      => true,
            ],
            [
                'judul'      => 'Portofolio Website',
                'slug'       => 'portofolio',
                'url'        => 'https://rizki-habibi-portofolio.vercel.app',
                'deskripsi'  => 'Kunjungi portofolio Rizki Habibi — project, skill, pengalaman, dan kontak.',
                'ikon'       => '🚀',
                'warna_bg'   => '#FFE600',
                'warna_teks' => '#1A1A2E',
                'urutan'     => 13,
                'aktif'      => true,
                'unggulan'   => true,
            ],
            [
                'judul'      => 'LinkedIn',
                'slug'       => 'linkedin',
                'url'        => 'https://linkedin.com',
                'deskripsi'  => 'Connect di LinkedIn Rizki Habibi — networking profesional dan peluang kolaborasi.',
                'ikon'       => '💼',
                'warna_bg'   => '#0A66C2',
                'warna_teks' => '#FFFFFF',
                'urutan'     => 14,
                'aktif'      => true,
            ],
            [
                'judul'      => 'Fiverr — Jasa Freelance',
                'slug'       => 'fiverr',
                'url'        => 'https://www.fiverr.com/rizkihub/buying?source=avatar_menu_profile',
                'deskripsi'  => 'Pesan jasa freelance Rizki Habibi di Fiverr — web development, desain, dan project digital lainnya dengan harga terjangkau.',
                'ikon'       => '💰',
                'warna_bg'   => '#1DBF73',
                'warna_teks' => '#FFFFFF',
                'urutan'     => 15,
                'aktif'      => true,
                'unggulan'   => true,
            ],
            [
                'judul'      => 'Lazada — Profil Toko',
                'slug'       => 'lazada-akun',
                'url'        => 'https://member.lazada.co.id/user/profile?spm=a2o42.manage_account.0.0.545e514b0rQnW9#/profile/my',
                'deskripsi'  => 'Kunjungi profil toko Rizki Habibi di Lazada — produk pilihan, promo menarik, dan harga terbaik.',
                'ikon'       => '🛒',
                'warna_bg'   => '#F57224',
                'warna_teks' => '#FFFFFF',
                'urutan'     => 16,
                'aktif'      => true,
            ],

            // ─── Donasi & Support (19–20) ────────────────────────────
            [
                'judul'      => 'Trakteer — Support Rizki',
                'slug'       => 'trakteer',
                'url'        => 'https://trakteer.id',
                'deskripsi'  => 'Dukung konten Rizki dengan traktir kopi — setiap dukungan sangat berarti!',
                'ikon'       => '☕',
                'warna_bg'   => '#E53935',
                'warna_teks' => '#FFFFFF',
                'urutan'     => 19,
                'aktif'      => true,
            ],
            [
                'judul'      => 'Saweria — Donasi',
                'slug'       => 'saweria',
                'url'        => 'https://saweria.co',
                'deskripsi'  => 'Bantu Rizki terus berkarya dengan donasi di Saweria — berapapun sangat membantu!',
                'ikon'       => '🍵',
                'warna_bg'   => '#FF6B35',
                'warna_teks' => '#FFFFFF',
                'urutan'     => 20,
                'aktif'      => true,
            ],

            // ─── Konten & Lainnya (21–25) ────────────────────────────
            [
                'judul'      => 'Blog / Medium',
                'slug'       => 'blog',
                'url'        => 'https://medium.com',
                'deskripsi'  => 'Baca artikel dan tutorial Rizki Habibi seputar teknologi.',
                'ikon'       => '✍️',
                'warna_bg'   => '#00AB6C',
                'warna_teks' => '#FFFFFF',
                'urutan'     => 21,
                'aktif'      => true,
            ],
            [
                'judul'      => 'Spotify Playlist',
                'slug'       => 'spotify',
                'url'        => 'https://open.spotify.com',
                'deskripsi'  => 'Dengerin playlist favorit Rizki sambil coding!',
                'ikon'       => '🎧',
                'warna_bg'   => '#1DB954',
                'warna_teks' => '#FFFFFF',
                'urutan'     => 22,
                'aktif'      => true,
            ],
            [
                'judul'      => 'Email Saya',
                'slug'       => 'email',
                'url'        => 'mailto:rizkihabibi@example.com',
                'deskripsi'  => 'Kirim email ke Rizki untuk kolaborasi, pertanyaan, atau kerja sama.',
                'ikon'       => '📧',
                'warna_bg'   => '#EA4335',
                'warna_teks' => '#FFFFFF',
                'urutan'     => 23,
                'aktif'      => true,
            ],

            // ─── Project & Repo GitHub (26–99) ──────────────────────
            [
                'judul'      => 'BerbagiTautan — Link in Bio',
                'slug'       => 'repo-berbagi-tautan',
                'url'        => 'https://github.com/rizki-habibi/berbagi-tautan',
                'deskripsi'  => 'Source code BerbagiTautan — clone Linktree bergaya komik dibuat dengan Laravel + Vite.',
                'ikon'       => '🔗',
                'warna_bg'   => '#FF6B35',
                'warna_teks' => '#FFFFFF',
                'urutan'     => 26,
                'aktif'      => true,
            ],
            [
                'judul'      => 'Portofolio Rizki Habibi',
                'slug'       => 'repo-portofolio',
                'url'        => 'https://rizki-habibi-portofolio.vercel.app',
                'deskripsi'  => 'Website portofolio bergaya Sakamoto Days — React + Next.js + Tailwind.',
                'ikon'       => '🎨',
                'warna_bg'   => '#6C3483',
                'warna_teks' => '#FFFFFF',
                'urutan'     => 27,
                'aktif'      => true,
            ],
            [
                'judul'      => 'VTA — Virtual Creators Archive',
                'slug'       => 'repo-vta',
                'url'        => 'https://vta-five.vercel.app',
                'deskripsi'  => 'RESTORE — 7-panel manga-style mystery comic. VTA Virtual Creators Archive.',
                'ikon'       => '🎭',
                'warna_bg'   => '#16213E',
                'warna_teks' => '#FFE600',
                'urutan'     => 28,
                'aktif'      => true,
            ],
            [
                'judul'      => 'VTO Portfolio',
                'slug'       => 'repo-vto',
                'url'        => 'https://vto-portfolio.vercel.app',
                'deskripsi'  => 'VTO Portfolio — Visi, Teknologi, Organisasi. React + Vite + Framer Motion.',
                'ikon'       => '⚡',
                'warna_bg'   => '#0D7377',
                'warna_teks' => '#FFFFFF',
                'urutan'     => 29,
                'aktif'      => true,
            ],
            [
                'judul'      => 'KVT Project Hub',
                'slug'       => 'repo-kvt',
                'url'        => 'https://kvt-project-hub.vercel.app',
                'deskripsi'  => 'Comic-style Event & Magang Hub — Next.js 15 + Tailwind CSS v4.',
                'ikon'       => '📋',
                'warna_bg'   => '#2C3E50',
                'warna_teks' => '#FFE600',
                'urutan'     => 30,
                'aktif'      => true,
            ],
            [
                'judul'      => 'VirtualKarakter',
                'slug'       => 'repo-virtual-karakter',
                'url'        => 'https://github.com/rizki-habibi/VirtualKarakter',
                'deskripsi'  => 'Sistem animasi karakter virtual berbasis video — fitur bahasa Indonesia, background virtual, streaming browser.',
                'ikon'       => '🤖',
                'warna_bg'   => '#1A1A2E',
                'warna_teks' => '#00BCD4',
                'urutan'     => 31,
                'aktif'      => true,
            ],
            [
                'judul'      => 'Vexora',
                'slug'       => 'repo-vexora',
                'url'        => 'https://github.com/rizki-habibi/vexora',
                'deskripsi'  => 'Project Vexora — dibuat dengan Laravel + Blade.',
                'ikon'       => '✨',
                'warna_bg'   => '#8E44AD',
                'warna_teks' => '#FFFFFF',
                'urutan'     => 32,
                'aktif'      => true,
            ],
            [
                'judul'      => 'Sistem SPK WP & SAW',
                'slug'       => 'repo-spk',
                'url'        => 'https://github.com/rizki-habibi/fitur-spk-wp-dan-saw',
                'deskripsi'  => 'Sistem Pendukung Keputusan metode WP dan SAW — dibuat dengan Laravel.',
                'ikon'       => '📊',
                'warna_bg'   => '#27AE60',
                'warna_teks' => '#FFFFFF',
                'urutan'     => 33,
                'aktif'      => true,
            ],
            [
                'judul'      => 'KKN Leguler Puger Grenden',
                'slug'       => 'repo-kkn',
                'url'        => 'https://github.com/rizki-habibi/KKN-leguler-puger-grenden',
                'deskripsi'  => 'Website KKN Leguler Puger Grenden — TypeScript + modern stack.',
                'ikon'       => '🏡',
                'warna_bg'   => '#E67E22',
                'warna_teks' => '#FFFFFF',
                'urutan'     => 34,
                'aktif'      => true,
            ],
        ];

        foreach ($links as $link) {
            Link::create($link);
        }
    }
}
